# 공통 환경

spring:
  security:
    user:
      name: crash-admin
      password: crash-admin-password

# profile 설정 - application-{spring:profiles:active}.yml
---
spring:
  profiles:
    active: dev
---
spring:
  profiles:
    active: prod
---
