# 프로덕션 환경

spring:
  datasource:
    username: sa
    password: sa
    url: jdbc:h2:tcp://localhost/~/demo
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug